project_id = "mcmfwlgovubpdcfiqfvk"

[functions.submit-application]
[functions.google-places]
[functions.google-place-details]
[functions.enrich-feasibility]
verify_jwt = false
[functions.enrich-utilities]
verify_jwt = false